import { Employee, ApprovalRequest, EmployeeDocument, Survey, NotificationItem, User } from '@/types';

export const DEMO_USERS: Record<string, User> = {
  EMPLOYEE: {
    id: 101,
    name: 'Alex Rivera',
    email: 'alex.rivera@worksphere.com',
    role: 'EMPLOYEE',
    department: 'Engineering',
    title: 'Frontend Software Engineer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  MANAGER: {
    id: 102,
    name: 'Sarah Connor',
    email: 'sarah.connor@worksphere.com',
    role: 'MANAGER',
    department: 'Engineering',
    title: 'Engineering Director',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  HR_ADMIN: {
    id: 103,
    name: 'Michael Vance',
    email: 'michael.vance@worksphere.com',
    role: 'HR_ADMIN',
    department: 'HR',
    title: 'Chief Human Resources Officer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
};

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 101,
    name: 'Alex Rivera',
    email: 'alex.rivera@worksphere.com',
    phone: '+1 (555) 234-5678',
    department: 'Engineering',
    title: 'Frontend Software Engineer',
    role: 'EMPLOYEE',
    status: 'Active',
    startDate: '2023-03-15',
    experienceYears: 4,
    skills: ['React', 'TypeScript', 'Redux', 'CSS3', 'Jest'],
    managerName: 'Sarah Connor',
    location: 'San Francisco, CA',
    bio: 'Passionate about building scalable UI components and enterprise web applications.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 102,
    name: 'Sarah Connor',
    email: 'sarah.connor@worksphere.com',
    phone: '+1 (555) 345-6789',
    department: 'Engineering',
    title: 'Engineering Director',
    role: 'MANAGER',
    status: 'Active',
    startDate: '2020-01-10',
    experienceYears: 10,
    skills: ['System Design', 'React', 'Node.js', 'PostgreSQL', 'Leadership'],
    managerName: 'Michael Vance',
    location: 'San Francisco, CA',
    bio: 'Tech leader scaling web infrastructure and engineering culture.',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 103,
    name: 'Michael Vance',
    email: 'michael.vance@worksphere.com',
    phone: '+1 (555) 456-7890',
    department: 'HR',
    title: 'Chief Human Resources Officer',
    role: 'HR_ADMIN',
    status: 'Active',
    startDate: '2019-06-01',
    experienceYears: 12,
    skills: ['Talent Management', 'HR Policy', 'Employee Relations', 'Analytics'],
    location: 'New York, NY',
    bio: 'HR strategist optimizing talent growth and workplace engagement.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 104,
    name: 'Elena Rostova',
    email: 'elena.r@worksphere.com',
    phone: '+1 (555) 567-8901',
    department: 'Design',
    title: 'Lead Product Designer',
    role: 'EMPLOYEE',
    status: 'Active',
    startDate: '2022-09-01',
    experienceYears: 6,
    skills: ['Figma', 'UI/UX', 'Design Systems', 'User Research'],
    managerName: 'Sarah Connor',
    location: 'Austin, TX',
    bio: 'Crafting intuitive UI interfaces and modern enterprise design language.',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 105,
    name: 'David Chen',
    email: 'david.chen@worksphere.com',
    phone: '+1 (555) 678-9012',
    department: 'Engineering',
    title: 'Senior Backend Engineer',
    role: 'EMPLOYEE',
    status: 'On Leave',
    startDate: '2021-11-15',
    experienceYears: 7,
    skills: ['Go', 'PostgreSQL', 'Docker', 'Kubernetes', 'Redis'],
    managerName: 'Sarah Connor',
    location: 'Seattle, WA',
    bio: 'Distributed systems engineer focusing on high-throughput microservices.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 106,
    name: 'Priya Sharma',
    email: 'priya.s@worksphere.com',
    phone: '+1 (555) 789-0123',
    department: 'Finance',
    title: 'Financial Planning Manager',
    role: 'MANAGER',
    status: 'Active',
    startDate: '2021-04-01',
    experienceYears: 8,
    skills: ['Financial Modeling', 'Budgeting', 'Excel', 'Corporate Finance'],
    managerName: 'Michael Vance',
    location: 'Chicago, IL',
    bio: 'Managing corporate budgets and financial operations analytics.',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 107,
    name: 'James Wilson',
    email: 'james.w@worksphere.com',
    phone: '+1 (555) 890-1234',
    department: 'Product',
    title: 'Senior Product Manager',
    role: 'MANAGER',
    status: 'Active',
    startDate: '2022-01-20',
    experienceYears: 9,
    skills: ['Roadmapping', 'Agile', 'Product Analytics', 'User Stories'],
    managerName: 'Michael Vance',
    location: 'San Francisco, CA',
    bio: 'Driving product strategy and cross-functional team execution.',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 108,
    name: 'Sophia Martinez',
    email: 'sophia.m@worksphere.com',
    phone: '+1 (555) 901-2345',
    department: 'Marketing',
    title: 'Growth Marketing Specialist',
    role: 'EMPLOYEE',
    status: 'Active',
    startDate: '2023-07-10',
    experienceYears: 3,
    skills: ['SEO', 'Content Strategy', 'Google Analytics', 'Campaigns'],
    managerName: 'James Wilson',
    location: 'Miami, FL',
    bio: 'Optimizing acquisition funnels and digital marketing growth.',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 109,
    name: 'Marcus Brody',
    email: 'marcus.b@worksphere.com',
    phone: '+1 (555) 012-3456',
    department: 'HR',
    title: 'HR Specialist',
    role: 'HR_ADMIN',
    status: 'Active',
    startDate: '2023-01-05',
    experienceYears: 5,
    skills: ['Onboarding', 'Payroll', 'Compliance', 'Workday'],
    managerName: 'Michael Vance',
    location: 'New York, NY',
    bio: 'Streamlining employee onboarding and HR operations compliance.',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 110,
    name: 'Chloe Kim',
    email: 'chloe.kim@worksphere.com',
    phone: '+1 (555) 123-4567',
    department: 'Engineering',
    title: 'DevOps Engineer',
    role: 'EMPLOYEE',
    status: 'Inactive',
    startDate: '2022-05-15',
    experienceYears: 5,
    skills: ['AWS', 'Terraform', 'CI/CD', 'GitHub Actions'],
    managerName: 'Sarah Connor',
    location: 'Denver, CO',
    bio: 'Cloud architecture automation and continuous integration infrastructure.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_REQUESTS: ApprovalRequest[] = [
  {
    id: 'REQ-1001',
    employeeId: 101,
    employeeName: 'Alex Rivera',
    department: 'Engineering',
    category: 'Leave',
    title: 'Annual Vacation Leave',
    description: 'Requesting 5 business days off for annual family trip.',
    startDate: '2026-09-15',
    endDate: '2026-09-22',
    status: 'PENDING',
    createdAt: '2026-09-01T10:30:00Z',
    updatedAt: '2026-09-01T10:30:00Z',
    timeline: [
      { stage: 'Submitted', status: 'COMPLETED', actionBy: 'Alex Rivera', actionDate: '2026-09-01 10:30' },
      { stage: 'Manager Review', status: 'PENDING', actionBy: 'Sarah Connor' },
      { stage: 'HR Review', status: 'PENDING', actionBy: 'Michael Vance' },
      { stage: 'Final Completion', status: 'PENDING' },
    ],
  },
  {
    id: 'REQ-1002',
    employeeId: 104,
    employeeName: 'Elena Rostova',
    department: 'Design',
    category: 'Equipment',
    title: 'MacBook Pro M3 Max Upgrade',
    description: 'Upgrade request for high-resolution 3D design and Figma rendering.',
    amount: 3499,
    status: 'MANAGER_APPROVED',
    createdAt: '2026-08-28T14:15:00Z',
    updatedAt: '2026-08-30T09:20:00Z',
    timeline: [
      { stage: 'Submitted', status: 'COMPLETED', actionBy: 'Elena Rostova', actionDate: '2026-08-28 14:15' },
      { stage: 'Manager Review', status: 'COMPLETED', actionBy: 'Sarah Connor', actionDate: '2026-08-30 09:20', comment: 'Approved. Hardware update is necessary for design workflow.' },
      { stage: 'HR Review', status: 'PENDING', actionBy: 'Michael Vance' },
      { stage: 'Final Completion', status: 'PENDING' },
    ],
  },
  {
    id: 'REQ-1003',
    employeeId: 105,
    employeeName: 'David Chen',
    department: 'Engineering',
    category: 'Training',
    title: 'Kubernetes CKA Certification Course',
    description: 'Enrolling in Certified Kubernetes Administrator exam and prep bootcamp.',
    amount: 599,
    status: 'COMPLETED',
    createdAt: '2026-08-10T11:00:00Z',
    updatedAt: '2026-08-15T16:45:00Z',
    timeline: [
      { stage: 'Submitted', status: 'COMPLETED', actionBy: 'David Chen', actionDate: '2026-08-10 11:00' },
      { stage: 'Manager Review', status: 'COMPLETED', actionBy: 'Sarah Connor', actionDate: '2026-08-12 15:10', comment: 'Great initiative!' },
      { stage: 'HR Review', status: 'COMPLETED', actionBy: 'Michael Vance', actionDate: '2026-08-15 16:45', comment: 'Budget allocated under Engineering L&D.' },
      { stage: 'Final Completion', status: 'COMPLETED', actionBy: 'System', actionDate: '2026-08-15 16:45' },
    ],
  },
  {
    id: 'REQ-1004',
    employeeId: 108,
    employeeName: 'Sophia Martinez',
    department: 'Marketing',
    category: 'Remote Work',
    title: 'Remote Work Month - October',
    description: 'Requesting permission to work remotely from Miami during October.',
    status: 'REJECTED',
    createdAt: '2026-08-20T08:45:00Z',
    updatedAt: '2026-08-22T11:30:00Z',
    rejectionReason: 'On-site presence required for upcoming Q4 marketing campaign kickoff.',
    timeline: [
      { stage: 'Submitted', status: 'COMPLETED', actionBy: 'Sophia Martinez', actionDate: '2026-08-20 08:45' },
      { stage: 'Manager Review', status: 'REJECTED', actionBy: 'James Wilson', actionDate: '2026-08-22 11:30', comment: 'On-site presence required for upcoming Q4 marketing campaign kickoff.' },
      { stage: 'HR Review', status: 'SKIPPED' },
      { stage: 'Final Completion', status: 'REJECTED' },
    ],
  },
];

export const INITIAL_DOCUMENTS: EmployeeDocument[] = [
  {
    id: 'DOC-501',
    employeeId: 101,
    employeeName: 'Alex Rivera',
    name: 'Alex_Rivera_Passport.pdf',
    category: 'Passport',
    sizeBytes: 2450000,
    uploadedAt: '2026-09-01T09:00:00Z',
    status: 'APPROVED',
  },
  {
    id: 'DOC-502',
    employeeId: 101,
    employeeName: 'Alex Rivera',
    name: 'React_Expert_Certificate.pdf',
    category: 'Certificates',
    sizeBytes: 1200000,
    uploadedAt: '2026-09-02T11:30:00Z',
    status: 'PENDING',
  },
  {
    id: 'DOC-503',
    employeeId: 104,
    employeeName: 'Elena Rostova',
    name: 'Elena_ID_Proof.pdf',
    category: 'ID Proof',
    sizeBytes: 3100000,
    uploadedAt: '2026-08-25T14:20:00Z',
    status: 'REUPLOAD_REQUESTED',
    rejectionReason: 'Document image blurry. Please upload a clear color scan of passport/ID.',
  },
  {
    id: 'DOC-504',
    employeeId: 105,
    employeeName: 'David Chen',
    name: 'Offer_Letter_Signed.pdf',
    category: 'Offer Letter',
    sizeBytes: 890000,
    uploadedAt: '2021-11-10T16:00:00Z',
    status: 'APPROVED',
  },
];

export const INITIAL_SURVEYS: Survey[] = [
  {
    id: 'SURVEY-2026-Q3',
    title: 'Q3 Enterprise Employee Satisfaction & Workplace Culture Survey',
    description: 'Help us improve developer experience, benefits, and leadership transparency by filling out this quick 3-step feedback survey.',
    isActive: true,
    createdAt: '2026-08-15',
    sections: [
      {
        id: 'sec-1',
        title: 'Workplace & Role Satisfaction',
        description: 'Tell us how you feel about your current responsibilities and team dynamic.',
        questions: [
          {
            id: 'q1',
            type: 'radio',
            label: 'How satisfied are you with your current role and responsibilities?',
            required: true,
            options: ['Very Satisfied', 'Satisfied', 'Neutral', 'Dissatisfied', 'Very Dissatisfied'],
          },
          {
            id: 'q2',
            type: 'select',
            label: 'How would you rate work-life balance in your department?',
            required: true,
            options: ['Excellent', 'Good', 'Average', 'Needs Improvement', 'Poor'],
          },
          {
            id: 'q3',
            type: 'text',
            label: 'What is one project highlight or win from the past quarter?',
            required: false,
            placeholder: 'e.g. Migration to Redux Toolkit & Saga architecture...',
          },
        ],
      },
      {
        id: 'sec-2',
        title: 'Growth & Leadership',
        description: 'Provide feedback on career development support and manager clarity.',
        questions: [
          {
            id: 'q4',
            type: 'radio',
            label: 'Do you feel you have clear growth opportunities and mentorship?',
            required: true,
            options: ['Strongly Agree', 'Agree', 'Neutral', 'Disagree', 'Strongly Disagree'],
          },
          {
            id: 'q5',
            type: 'checkbox',
            label: 'Which learning & development benefits would you like to see expanded?',
            required: false,
            options: ['Tech Conference Budget', 'Online Course Stipend', 'Internal Hackathons', 'Leadership Coaching'],
          },
        ],
      },
      {
        id: 'sec-3',
        title: 'Final Feedback & Open Comments',
        description: 'Any additional ideas or constructive feedback for leadership.',
        questions: [
          {
            id: 'q6',
            type: 'email',
            label: 'Work Email (Optional for direct follow-up)',
            required: false,
            placeholder: 'alex.rivera@worksphere.com',
          },
          {
            id: 'q7',
            type: 'textarea',
            label: 'What changes or improvements would make WorkSphere a 10/10 workplace?',
            required: true,
            placeholder: 'Share your honest feedback...',
          },
        ],
      },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-1',
    title: 'Request Status Updated',
    message: 'Your leave request #REQ-1001 is currently pending Manager review.',
    type: 'info',
    createdAt: '2026-09-01T10:31:00Z',
    read: false,
    link: '/requests',
  },
  {
    id: 'NOTIF-2',
    title: 'Document Action Required',
    message: 'Elena Rostova has a document pending re-upload approval.',
    type: 'warning',
    createdAt: '2026-08-25T14:22:00Z',
    read: false,
    link: '/documents',
  },
  {
    id: 'NOTIF-3',
    title: 'Q3 Survey Available',
    message: 'The Q3 Enterprise Employee Satisfaction Survey is now live. Please complete by Sept 20.',
    type: 'success',
    createdAt: '2026-08-15T09:00:00Z',
    read: true,
    link: '/surveys',
  },
];
